/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 인증 요청 신청자 정보
 */
export interface ApplicantInfoDto { 
    userId?: number;
    name?: string;
    nickname?: string;
    email?: string;
    phone?: string;
    gender?: ApplicantInfoDto.GenderEnum;
    profileImg?: string;
}
export namespace ApplicantInfoDto {
    export type GenderEnum = 'F' | 'M' | 'UNDEFINED';
    export const GenderEnum = {
        F: 'F' as GenderEnum,
        M: 'M' as GenderEnum,
        UNDEFINED: 'UNDEFINED' as GenderEnum
    };
}