/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 결제 취소 dto
 */
export interface CancelReqDto { 
    /**
     * 결제했던 트레이닝 id
     */
    trainingId: number;
    /**
     * 결제 내역 id
     */
    reservationId: number;
    /**
     * 포트원 거래고유번호
     */
    impUid: string;
    /**
     * 결제했던 금액(환불 금액)
     */
    amount: string;
}