/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이너 인증 요청을 거절하는 이유
 */
export interface CertRejectDto { 
    /**
     * 거절 타입
     */
    rejectType: CertRejectDto.RejectTypeEnum;
    /**
     * 거절하는 상세한 설명이 필요하다면 작성
     */
    reason?: string;
}
export namespace CertRejectDto {
    export type RejectTypeEnum = 'INVALID_CERTIFICATE' | 'UNPROVABLE_CAREER';
    export const RejectTypeEnum = {
        INVALIDCERTIFICATE: 'INVALID_CERTIFICATE' as RejectTypeEnum,
        UNPROVABLECAREER: 'UNPROVABLE_CAREER' as RejectTypeEnum
    };
}