/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 관리자 - 트레이너 인증 요청 전체 조회 시 사용하는 요약 정보
 */
export interface CertRequestOutlineDto { 
    requestId?: number;
    userName?: string;
    userEmail?: string;
    requestDateTime?: Date;
}