/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Document } from './document';

export interface ChatRoomResponseDto {
  /**
   * 채팅방 id
   */
  roomId?: number;
  /**
   * 채팅상대 이름(채팅방 이름)
   */
  roomName?: string;
  senderProfileImg?: Document;
  /**
   * 채팅방 수정일
   */
  lastMessageDate?: Date;
  /**
   * 마지막 채팅 내용
   */
  lastMessage?: string;
  /**
   * 안읽은 채팅 개수
   */
  unreadChatCount?: number;
}
