/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Document } from './document';

export interface ChatMessageResponseDto { 
    /**
     * 메세지 id
     */
    messageId?: number;
    /**
     * 발신자 id
     */
    senderId?: number;
    /**
     * 발신자 닉네임
     */
    senderNickname?: string;
    senderProfileImg?: Document;
    /**
     * 메세지 내용
     */
    message?: string;
    /**
     * 메세지 생성일
     */
    createdDate?: Date;
}