/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 게시글 댓글 리스트
 */
export interface CommentInfoDto { 
    commentId?: number;
    writerNickName?: string;
    content?: string;
    parentCommentId?: number;
    profileUrl?: string;
    profileInputName?: string;
    deleted?: boolean;
    createdDate?: Date;
    childComment?: Array<CommentInfoDto>;
}