/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 댓글 수정 dto
 */
export interface CommentUpdateDto { 
    /**
     * 댓글 내용
     */
    content: string;
    /**
     * 댓글 Id
     */
    commentId: number;
}