/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 게시글 좋아요 정보 dto
 */
export interface LikesInfoDto { 
    /**
     * 게시글 좋아요한 사용자의 닉네임
     */
    nickname?: string;
    /**
     * 게시글 좋아요한 사용자의 프로필
     */
    profileUrl?: string;
}