/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 알림 dto
 */
export interface NotifyDto { 
    /**
     * 알림 primary key
     */
    id: number;
    /**
     * 알림 내용
     */
    content: string;
    /**
     * 클릭 시 이동할 주소
     */
    url: string;
    /**
     * 알림 타입
     */
    type: NotifyDto.TypeEnum;
    /**
     * 알림 읽음 / 안 읽음
     */
    read: boolean;
    /**
     * 알림 생성일
     */
    createDate?: Date;
    /**
     * 알림 수정일 -> 알림 읽은 시간
     */
    modifiedDate?: Date;
}
export namespace NotifyDto {
    export type TypeEnum = 'COMMENT' | 'LIKE_POST' | 'TRAINER_AUTHENTICATION_ACCEPT' | 'TRAINER_AUTHENTICATION_REJECT' | 'NEW_RESERVATION' | 'CANCEL_RESERVATION' | 'NEW_REVIEW' | 'NOSHOW' | 'NEW_CHAT';
    export const TypeEnum = {
        COMMENT: 'COMMENT' as TypeEnum,
        LIKEPOST: 'LIKE_POST' as TypeEnum,
        TRAINERAUTHENTICATIONACCEPT: 'TRAINER_AUTHENTICATION_ACCEPT' as TypeEnum,
        TRAINERAUTHENTICATIONREJECT: 'TRAINER_AUTHENTICATION_REJECT' as TypeEnum,
        NEWRESERVATION: 'NEW_RESERVATION' as TypeEnum,
        CANCELRESERVATION: 'CANCEL_RESERVATION' as TypeEnum,
        NEWREVIEW: 'NEW_REVIEW' as TypeEnum,
        NOSHOW: 'NOSHOW' as TypeEnum,
        NEWCHAT: 'NEW_CHAT' as TypeEnum
    };
}