/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 최 상위 댓글 정보 dto
 */
export interface ParentCommentInfoDto { 
    /**
     * 댓글 id
     */
    commentId?: number;
    /**
     * 댓글 작성자의 id
     */
    writerId?: number;
    /**
     * 댓글 작성자의 닉네임
     */
    writerNickName?: string;
    /**
     * 
     */
    writerEmail?: string;
    /**
     * 댓글 내용
     */
    content?: string;
    /**
     * 댓글 작성자의 프로필 url
     */
    writerProfileUrl?: string;
    /**
     * 댓글 생성일
     */
    createdDate?: Date;
    /**
     * 댓글 수정일
     */
    modifiedDate?: Date;
    /**
     * 자식 답글 존재 여부
     */
    hasChildComment?: boolean;
}