/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 결제 완료 후 보내주는 응답 데이터, 결제 정보가 들어있음
 */
export interface PaymentResDto { 
    impUid?: string;
    merchantUid?: string;
    /**
     * 현재 카드 결제만 되므로 card라고만 있을 것
     */
    payMethod?: string;
    /**
     * 결제 금액
     */
    amount?: number;
    /**
     * 트레이닝 id
     */
    trainingId?: number;
    /**
     * 트레이닝 제목
     */
    title?: string;
    /**
     * 트레이닝 예약 시간
     */
    reservationDateTime?: Date;
    /**
     * 결제 진행된 시간
     */
    paymentDateTime?: Date;
}