/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostWriterInfoDto } from './postWriterInfoDto';

/**
 * 게시글 정보 dto
 */
export interface PostInfoDto { 
    /**
     * 게시글 id
     */
    postId?: number;
    writerInfo?: PostWriterInfoDto;
    /**
     * 게시글 생성일
     */
    createdDate?: Date;
    /**
     * 게시글 수정일
     */
    modifiedDate?: Date;
    /**
     * 게시글 내용
     */
    content?: string;
    /**
     * 게시글 해시태그
     */
    hashTags?: Array<string>;
    /**
     * 게시글 조회수
     */
    views?: number;
    /**
     * 게시글 첨부 이미지 url 리스트
     */
    documentUrls?: Array<string>;
    /**
     * 게시글 댓글 수
     */
    postCommentsCount?: number;
}