/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentInfoDto } from './commentInfoDto';
import { PostOutlineDto } from './postOutlineDto';

/**
 * 게시글 세부 정보 dto
 */
export interface PostDetailInfoDto {
  postOutlineDto: PostOutlineDto;
  /**
   * 게시글 댓글 리스트
   */
  postComments: Array<CommentInfoDto>;
}
