/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LikedUsersInfoDto } from './likedUsersInfoDto';
import { PostInfoDto } from './postInfoDto';

/**
 * 게시글 요약 정보 dto
 */
export interface PostOutlineDto {
  postInfo: PostInfoDto;
  postLikedInfo: LikedUsersInfoDto;
  /**
   * 게시글 댓글 수
   */
  postCommentsCount: number;
}
