/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 전체 게시글 조회 시 받은 response body의 게시글 id
 */
export interface PostRequestDto {
  /**
   * 게시글 id
   */
  postId?: number;
}
