/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 게시글 작성자 정보 dto
 */
export interface PostWriterInfoDto { 
    /**
     * 작성자 닉네임
     */
    nickname?: string;
    /**
     * 게시글 작성자 프로필 url
     */
    profileUrl?: string;
}