/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 프로필 수정 dto
 */
export interface ProfileUpdateDto { 
    name?: string;
    nickname?: string;
    phone?: string;
    gender?: ProfileUpdateDto.GenderEnum;
    bio?: string;
}
export namespace ProfileUpdateDto {
    export type GenderEnum = 'F' | 'M' | 'UNDEFINED';
    export const GenderEnum = {
        F: 'F' as GenderEnum,
        M: 'M' as GenderEnum,
        UNDEFINED: 'UNDEFINED' as GenderEnum
    };
}