/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 결제 검증 후 정보 저장을 위한 dto
 */
export interface ReserveReqDto { 
    /**
     * 예약할 트레이닝의 id
     */
    trainingId: number;
    /**
     * 상점 id kc는 html5_inicis 아니면 inicis
     */
    pg: string;
    /**
     * 결제 방법
     */
    payMethod: string;
    /**
     * 포트원 거래고유번호
     */
    impUid: string;
    /**
     * 주문 번호
     */
    merchantUid: string;
    /**
     * 가격
     */
    amount: number;
    /**
     * 예약한 날짜, 시간
     */
    reserveDateTime: Date;
}