/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 결제 금액 검증 전 예약 시간대 확인 및 저장을 위한 dto
 */
export interface ReserveReqDto {
  /**
   * 예약할 트레이닝의 id
   */
  trainingId: number;
  /**
   * 예약한 날짜, 시간
   */
  reserveDateTime: string;
}
