/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SignUpDto { 
    email: string;
    password: string;
    name: string;
    nickname: string;
    phone: string;
    bio?: string;
    gender: SignUpDto.GenderEnum;
    /**
     * 관심사 입력은 선택입니다. 여러 개 선택 가능합니다. ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
     */
    categories?: Array<SignUpDto.CategoriesEnum>;
}
export namespace SignUpDto {
    export type GenderEnum = 'F' | 'M' | 'UNDEFINED';
    export const GenderEnum = {
        F: 'F' as GenderEnum,
        M: 'M' as GenderEnum,
        UNDEFINED: 'UNDEFINED' as GenderEnum
    };
    export type CategoriesEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const CategoriesEnum = {
        PILATES: 'PILATES' as CategoriesEnum,
        HEALTH: 'HEALTH' as CategoriesEnum,
        PT: 'PT' as CategoriesEnum,
        CROSSFIT: 'CROSSFIT' as CategoriesEnum,
        YOGA: 'YOGA' as CategoriesEnum
    };
}