/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainingImgUpdateDto } from './trainingImgUpdateDto';

/**
 * 트레이닝 내용 수정 요청 Dto
 */
export interface TrainingContentUpdateDto { 
    title: string;
    content: string;
    price: number;
    trainingImgUpdateDto?: TrainingImgUpdateDto;
}