/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이너 추천 dto
 */
export interface TrainerRecommendationDto { 
    /**
     * 현재 일하는 장소
     */
    address?: string;
    /**
     * 트레이너 id
     */
    trainerId?: number;
    /**
     * 트레이너 이름
     */
    name?: string;
    /**
     * 트레이너 프로필 이미지
     */
    profileUrl?: string;
    /**
     * 트레이너 전문 분야
     */
    interests?: Array<TrainerRecommendationDto.InterestsEnum>;
    /**
     * 트레이너 평점
     */
    rating?: number;
    /**
     * 트레이너 후기 수
     */
    totalReviews?: number;
}
export namespace TrainerRecommendationDto {
    export type InterestsEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const InterestsEnum = {
        PILATES: 'PILATES' as InterestsEnum,
        HEALTH: 'HEALTH' as InterestsEnum,
        PT: 'PT' as InterestsEnum,
        CROSSFIT: 'CROSSFIT' as InterestsEnum,
        YOGA: 'YOGA' as InterestsEnum
    };
}