/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 내용 수정 - 이미지 수정에 사용
 */
export interface TrainingImgUpdateDto { 
    /**
     * 삭제된 이미지가 있다면 true로 주면 됨
     */
    imgDeleted?: boolean;
    /**
     * imgDeleted = true일 때만 주면 됨, 남아있는 이미지 url 리스트
     */
    unModifiedImgList?: Array<string>;
    /**
     * 새로 추가된 이미지가 있다면 true로
     */
    imgAdded?: boolean;
    /**
     * 새로 추가한 이미지
     */
    newImgList?: Array<Blob>;
}