/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 검색 조건
 */
export interface TrainingSearchConditionDto { 
    /**
     * 검색 키워드, 해당 검색 키워드가 포함되는 제목으로 검색
     */
    keyword?: string;
    /**
     * 최저가
     */
    lowestPrice?: number;
    /**
     * 최고가
     */
    highestPrice?: number;
    startDate?: string;
    endDate?: string;
    /**
     * 카테고리, 하나만 가능
     */
    category?: TrainingSearchConditionDto.CategoryEnum;
}
export namespace TrainingSearchConditionDto {
    export type CategoryEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const CategoryEnum = {
        PILATES: 'PILATES' as CategoryEnum,
        HEALTH: 'HEALTH' as CategoryEnum,
        PT: 'PT' as CategoryEnum,
        CROSSFIT: 'CROSSFIT' as CategoryEnum,
        YOGA: 'YOGA' as CategoryEnum
    };
}