/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainerInfoDto } from './trainerInfoDto';
import { TrainingAvailableDateDto } from './trainingAvailableDateDto';
import { TrainingDocumentDto } from './trainingDocumentDto';

export interface TrainingInfoDto { 
    id?: number;
    trainerInfoDto?: TrainerInfoDto;
    title?: string;
    content?: string;
    address?: string;
    images?: Array<TrainingDocumentDto>;
    price?: number;
    startDate?: string;
    endDate?: string;
    availableDates?: Array<TrainingAvailableDateDto>;
}