/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainerSearchCompanyDto { 
    /**
     * 근무 중인 회사명
     */
    company?: string;
    /**
     * 위도
     */
    latitude?: number;
    /**
     * 경도
     */
    longitude?: number;
}