/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainerCareerDto } from './trainerCareerDto';
import { TrainerLicenseDto } from './trainerLicenseDto';

export interface TrainerSpecDto { 
    trainerCareerList?: Array<TrainerCareerDto>;
    trainerLicenseList?: Array<TrainerLicenseDto>;
}