/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pageable } from './pageable';
import { TrainingSearchConditionDto } from './trainingSearchConditionDto';

export interface TrainingSearchBody { 
    conditions?: TrainingSearchConditionDto;
    pageable?: Pageable;
}