/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainerCareerDetailDto { 
    careerId: number;
    company: string;
    address: string;
    /**
     * 경도
     */
    longitude: number;
    /**
     * 위도
     */
    latitude: number;
    work: string;
    startDate: string;
    endDate?: string;
    working: boolean;
}