/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainerSearchFilterDto { 
    /**
     * 관심사(PILATES, HEALTH, PT, CROSSFIT, YOGA). 여러 개 선택 불가능
     */
    interest?: TrainerSearchFilterDto.InterestEnum;
    /**
     * 검색 키워드(트레이너 이름)
     */
    keyword?: string;
    /**
     * 성별 (F, M)
     */
    gender?: TrainerSearchFilterDto.GenderEnum;
}
export namespace TrainerSearchFilterDto {
    export type InterestEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const InterestEnum = {
        PILATES: 'PILATES' as InterestEnum,
        HEALTH: 'HEALTH' as InterestEnum,
        PT: 'PT' as InterestEnum,
        CROSSFIT: 'CROSSFIT' as InterestEnum,
        YOGA: 'YOGA' as InterestEnum
    };
    export type GenderEnum = 'F' | 'M' | 'UNDEFINED';
    export const GenderEnum = {
        F: 'F' as GenderEnum,
        M: 'M' as GenderEnum,
        UNDEFINED: 'UNDEFINED' as GenderEnum
    };
}