/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainersTrainingOutlineDto { 
    trainingId?: number;
    title?: string;
    price?: number;
    address?: string;
    participants?: number;
    startDate?: string;
    endDate?: string;
    closed?: boolean;
    createdDate?: Date;
    modifiedDate?: Date;
}