/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainerInfoDto } from './trainerInfoDto';

/**
 * 트레이닝 요약 정보 dto (트레이너 정보 포함)
 */
export interface TrainingOutlineDto { 
    id?: number;
    trainerInfoDto?: TrainerInfoDto;
    title?: string;
    price?: number;
    location?: string;
    startDate?: string;
    endDate?: string;
    closed?: boolean;
}