/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 생성 dto
 */
export interface TrainingCreateDto { 
    /**
     * 트레이닝 제목
     */
    title: string;
    /**
     * 트레이닝 소개글
     */
    content: string;
    images?: Array<Blob>;
    /**
     * 트레이닝이 진행 장소
     */
    location: string;
    /**
     * 가격
     */
    price?: number;
    /**
     * 트레이닝 시작 날짜
     */
    startDate?: string;
    /**
     * 트레이닝 마감 날짜
     */
    endDate?: string;
    /**
     * 트레이닝 예약 가능한 첫번째 시간
     */
    startHour?: string;
    /**
     * 트레이닝 예약 가능한 마지막 시간
     */
    endHour?: string;
    /**
     * 트레이닝 예약 날짜에서 트레이너가 안 된다고 체크한 날짜, 없으면 안 주면 됨
     */
    unableDates?: Array<string>;
}