/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 인증 요청 시 넣은 경력 리스트
 */
export interface TrainerCareerTempDto { 
    company?: string;
    address?: string;
    work?: string;
    startDate?: string;
    endDate?: string;
    working?: boolean;
}