/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainingDateUpdateDto { 
    /**
     * 트레이닝 시작 날짜, 달라지지 않았으면 기존의 날짜로
     */
    startDate: string;
    /**
     * 트레이닝 마지막 날짜, 달라지지 않았으면 기존의 날짜로
     */
    endDate: string;
    /**
     * 트레이닝 불가 날짜
     */
    unableDates?: Array<string>;
}