/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainerCareerRequestDto } from './trainerCareerRequestDto';

/**
 * 트레이너 인증 요청 dto
 */
export interface TrainerCertificationRequestDto { 
    /**
     * 트레이너 인증 요청 시 첨부한 자격증 파일 리스트
     */
    licenseFileList: Array<Blob>;
    /**
     * 트레이너 인증 요청 시 입력한 자격증 리스트
     */
    licenseNames: string;
    /**
     * 트레이너 인증 요청 시 작성한 경력사항
     */
    careerList: Array<TrainerCareerRequestDto>;
}