/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 카테고리 수정 요청 Dto
 */
export interface TrainingCategoryUpdateDto { 
    /**
     * 삭제된 카테고리가 있다면 true 로 주면 됨.
     */
    categoryDeleted?: boolean;
    /**
     * categoryDeleted = true 일 때만 주면 됨. (false 일 경우 빈 리스트로 전달) 수정되지 않는 카테고리 리스트. ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
     */
    unModifiedCategoryList?: Array<TrainingCategoryUpdateDto.UnModifiedCategoryListEnum>;
    /**
     * 새로 추가된 카테고리가 있다면 true 로 주면 됨.
     */
    categoryAdded?: boolean;
    /**
     * categoryAdded = true 일 때만 주면 됨. (false 일 경우 빈 리스트로 전달) 새로 추가한 카테고리. ex) PILATES, HEALTH, PT, CROSSFIT, YOGA
     */
    newCategoryList?: Array<TrainingCategoryUpdateDto.NewCategoryListEnum>;
}
export namespace TrainingCategoryUpdateDto {
    export type UnModifiedCategoryListEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const UnModifiedCategoryListEnum = {
        PILATES: 'PILATES' as UnModifiedCategoryListEnum,
        HEALTH: 'HEALTH' as UnModifiedCategoryListEnum,
        PT: 'PT' as UnModifiedCategoryListEnum,
        CROSSFIT: 'CROSSFIT' as UnModifiedCategoryListEnum,
        YOGA: 'YOGA' as UnModifiedCategoryListEnum
    };
    export type NewCategoryListEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const NewCategoryListEnum = {
        PILATES: 'PILATES' as NewCategoryListEnum,
        HEALTH: 'HEALTH' as NewCategoryListEnum,
        PT: 'PT' as NewCategoryListEnum,
        CROSSFIT: 'CROSSFIT' as NewCategoryListEnum,
        YOGA: 'YOGA' as NewCategoryListEnum
    };
}