/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TrainerOutlineDto { 
    /**
     * 현재 일하는 장소
     */
    address?: string;
    /**
     * 트레이너 id
     */
    id?: number;
    /**
     * 트레이너 이름
     */
    bio?: string;
    /**
     * 트레이너 이름
     */
    name?: string;
    /**
     * 트레이너 이메일
     */
    email?: string;
    /**
     * 트레이너 프로필 이미지
     */
    profileUrl?: string;
    /**
     * 트레이너 전문 분야
     */
    interests?: Array<TrainerOutlineDto.InterestsEnum>;
}
export namespace TrainerOutlineDto {
    export type InterestsEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const InterestsEnum = {
        PILATES: 'PILATES' as InterestsEnum,
        HEALTH: 'HEALTH' as InterestsEnum,
        PT: 'PT' as InterestsEnum,
        CROSSFIT: 'CROSSFIT' as InterestsEnum,
        YOGA: 'YOGA' as InterestsEnum
    };
}