/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 트레이닝 리뷰 작성 dto
 */
export interface TrainingReviewReqDto { 
    /**
     * 트레이닝 리뷰 작성을 위한 예약 내역의 id
     */
    reservationId: number;
    /**
     * 리뷰 작성 내용
     */
    content: string;
    /**
     * 회원이 주는 트레이닝 별점
     */
    star: number;
}