/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainingOutlineDto } from './trainingOutlineDto';

/**
 * 트레이닝 찜 리스트 조회 dto
 */
export interface TrainingLikesInfoDto { 
    /**
     * 트레이닝 찜 primary key
     */
    id?: number;
    trainingOutlineDto?: TrainingOutlineDto;
}