/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrainerCareerDto } from './trainerCareerDto';
import { TrainerLicenseDto } from './trainerLicenseDto';

export interface TrainerSpecDto { 
    trainerCareerList?: Array<TrainerCareerDto>;
    trainerLicenseList?: Array<TrainerLicenseDto>;
    /**
     * 트레이너 전문 분야
     */
    trainerExpertiseList?: Array<TrainerSpecDto.TrainerExpertiseListEnum>;
    address?: string;
}
export namespace TrainerSpecDto {
    export type TrainerExpertiseListEnum = 'PILATES' | 'HEALTH' | 'PT' | 'CROSSFIT' | 'YOGA';
    export const TrainerExpertiseListEnum = {
        PILATES: 'PILATES' as TrainerExpertiseListEnum,
        HEALTH: 'HEALTH' as TrainerExpertiseListEnum,
        PT: 'PT' as TrainerExpertiseListEnum,
        CROSSFIT: 'CROSSFIT' as TrainerExpertiseListEnum,
        YOGA: 'YOGA' as TrainerExpertiseListEnum
    };
}