/**
 * Fithub API Document
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Document } from './document';
import { OAuthSignUpDto } from './oAuthSignUpDto';

export interface User { 
    createdDate?: Date;
    modifiedDate?: Date;
    id?: number;
    password?: string;
    name: string;
    nickname: string;
    email: string;
    phone: string;
    gender: User.GenderEnum;
    grade: User.GradeEnum;
    status: User.StatusEnum;
    bio?: string;
    profileImg?: Document;
    roles?: Array<string>;
    provider?: string;
    providerId?: string;
    oauthSignUp?: OAuthSignUpDto;
}
export namespace User {
    export type GenderEnum = 'F' | 'M' | 'UNDEFINED';
    export const GenderEnum = {
        F: 'F' as GenderEnum,
        M: 'M' as GenderEnum,
        UNDEFINED: 'UNDEFINED' as GenderEnum
    };
    export type GradeEnum = 'INTRODUCTORY' | 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
    export const GradeEnum = {
        INTRODUCTORY: 'INTRODUCTORY' as GradeEnum,
        BEGINNER: 'BEGINNER' as GradeEnum,
        INTERMEDIATE: 'INTERMEDIATE' as GradeEnum,
        ADVANCED: 'ADVANCED' as GradeEnum
    };
    export type StatusEnum = 'NORMAL';
    export const StatusEnum = {
        NORMAL: 'NORMAL' as StatusEnum
    };
}